//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAirkxCompany.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.51book.com:8000/ltips/services/getAvailableFlightWithPriceAndCommisionS" +
            "ervice1.0")]
        public string ApiAirkxCompany_getAvailableFlightWithPriceAndCommision_GetAvailableFlightWithPriceAndCommisionServiceImpl_1_0Service {
            get {
                return ((string)(this["ApiAirkxCompany_getAvailableFlightWithPriceAndCommision_GetAvailableFlightWithPri" +
                    "ceAndCommisionServiceImpl_1_0Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.51book.com:8000/ltips/services/getChildPolicyAndFlightService1.0")]
        public string ApiAirkxCompany_getChildPolicyAndFlightService_GetChildPolicyAndFlightServiceImpl_1_0Service {
            get {
                return ((string)(this["ApiAirkxCompany_getChildPolicyAndFlightService_GetChildPolicyAndFlightServiceImpl" +
                    "_1_0Service"]));
            }
        }
    }
}
