//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace ApiAirkxCompany.GDSBookingServiceImp {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GDSBookingServiceImpl_1_0ServiceSoapBinding", Namespace="http://gdsbook.gds.service.version1_0.webservice.model.ltips.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(abstractLiantuoReply))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(abstractLiantuoRequest))]
    public partial class GDSBookingServiceImpl_1_0Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback gdsBookingOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GDSBookingServiceImpl_1_0Service() {
            this.Url = global::ApiAirkxCompany.Properties.Settings.Default.ApiAirkxCompany_GDSBookingServiceImp_GDSBookingServiceImpl_1_0Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event gdsBookingCompletedEventHandler gdsBookingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://gdsbook.gds.service.version1_0.webservice.model.ltips.com/", ResponseNamespace="http://gdsbook.gds.service.version1_0.webservice.model.ltips.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public gdsBookingReply gdsBooking([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] gdsBookingRequest request) {
            object[] results = this.Invoke("gdsBooking", new object[] {
                        request});
            return ((gdsBookingReply)(results[0]));
        }
        
        /// <remarks/>
        public void gdsBookingAsync(gdsBookingRequest request) {
            this.gdsBookingAsync(request, null);
        }
        
        /// <remarks/>
        public void gdsBookingAsync(gdsBookingRequest request, object userState) {
            if ((this.gdsBookingOperationCompleted == null)) {
                this.gdsBookingOperationCompleted = new System.Threading.SendOrPostCallback(this.OngdsBookingOperationCompleted);
            }
            this.InvokeAsync("gdsBooking", new object[] {
                        request}, this.gdsBookingOperationCompleted, userState);
        }
        
        private void OngdsBookingOperationCompleted(object arg) {
            if ((this.gdsBookingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.gdsBookingCompleted(this, new gdsBookingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gdsbook.gds.service.version1_0.webservice.model.ltips.com/")]
    public partial class gdsBookingRequest : abstractLiantuoRequest {
        
        private string[] contactsField;
        
        private string doPatField;
        
        private string doRTField;
        
        private string groupField;
        
        private string leaveDateField;
        
        private string leaveTimeField;
        
        private string officeNoField;
        
        private string param1Field;
        
        private string param2Field;
        
        private string param3Field;
        
        private wsBookingPassenger[] passengersField;
        
        private string pidNoField;
        
        private string pnrSourceField;
        
        private wsBookingSegment[] segmentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contacts", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] contacts {
            get {
                return this.contactsField;
            }
            set {
                this.contactsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string doPat {
            get {
                return this.doPatField;
            }
            set {
                this.doPatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string doRT {
            get {
                return this.doRTField;
            }
            set {
                this.doRTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string leaveDate {
            get {
                return this.leaveDateField;
            }
            set {
                this.leaveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string leaveTime {
            get {
                return this.leaveTimeField;
            }
            set {
                this.leaveTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string officeNo {
            get {
                return this.officeNoField;
            }
            set {
                this.officeNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param3 {
            get {
                return this.param3Field;
            }
            set {
                this.param3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("passengers", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public wsBookingPassenger[] passengers {
            get {
                return this.passengersField;
            }
            set {
                this.passengersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pidNo {
            get {
                return this.pidNoField;
            }
            set {
                this.pidNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pnrSource {
            get {
                return this.pnrSourceField;
            }
            set {
                this.pnrSourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("segments", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public wsBookingSegment[] segments {
            get {
                return this.segmentsField;
            }
            set {
                this.segmentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gdsbook.gds.service.version1_0.webservice.model.ltips.com/")]
    public partial class wsBookingPassenger {
        
        private string birthField;
        
        private string courseCardNoField;
        
        private string henchManField;
        
        private string identityNoField;
        
        private string identityTypeField;
        
        private string nameField;
        
        private string passengerTypeField;
        
        private string telePhoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string birth {
            get {
                return this.birthField;
            }
            set {
                this.birthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string courseCardNo {
            get {
                return this.courseCardNoField;
            }
            set {
                this.courseCardNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string henchMan {
            get {
                return this.henchManField;
            }
            set {
                this.henchManField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identityNo {
            get {
                return this.identityNoField;
            }
            set {
                this.identityNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identityType {
            get {
                return this.identityTypeField;
            }
            set {
                this.identityTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passengerType {
            get {
                return this.passengerTypeField;
            }
            set {
                this.passengerTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telePhone {
            get {
                return this.telePhoneField;
            }
            set {
                this.telePhoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gdsbook.gds.service.version1_0.webservice.model.ltips.com/")]
    public partial class wspnrTktNo {
        
        private string param1Field;
        
        private string param2Field;
        
        private string psgrIDField;
        
        private string remarkField;
        
        private string tktNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string psgrID {
            get {
                return this.psgrIDField;
            }
            set {
                this.psgrIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tktNo {
            get {
                return this.tktNoField;
            }
            set {
                this.tktNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gdsbook.gds.service.version1_0.webservice.model.ltips.com/")]
    public partial class wspnrAirSegment {
        
        private string actionCodeField;
        
        private int actionNumField;
        
        private bool actionNumFieldSpecified;
        
        private string arrTimeField;
        
        private string depDateField;
        
        private string depTimeField;
        
        private string dstCityField;
        
        private string flightNoField;
        
        private bool isEticketField;
        
        private bool isEticketFieldSpecified;
        
        private int lineIndexField;
        
        private bool lineIndexFieldSpecified;
        
        private string orgCityField;
        
        private string param1Field;
        
        private string param2Field;
        
        private string routeTypeField;
        
        private string seatCodeField;
        
        private string jetquayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string actionCode {
            get {
                return this.actionCodeField;
            }
            set {
                this.actionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int actionNum {
            get {
                return this.actionNumField;
            }
            set {
                this.actionNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actionNumSpecified {
            get {
                return this.actionNumFieldSpecified;
            }
            set {
                this.actionNumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arrTime {
            get {
                return this.arrTimeField;
            }
            set {
                this.arrTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string depDate {
            get {
                return this.depDateField;
            }
            set {
                this.depDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string depTime {
            get {
                return this.depTimeField;
            }
            set {
                this.depTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dstCity {
            get {
                return this.dstCityField;
            }
            set {
                this.dstCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string flightNo {
            get {
                return this.flightNoField;
            }
            set {
                this.flightNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isEticket {
            get {
                return this.isEticketField;
            }
            set {
                this.isEticketField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isEticketSpecified {
            get {
                return this.isEticketFieldSpecified;
            }
            set {
                this.isEticketFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int lineIndex {
            get {
                return this.lineIndexField;
            }
            set {
                this.lineIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lineIndexSpecified {
            get {
                return this.lineIndexFieldSpecified;
            }
            set {
                this.lineIndexFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orgCity {
            get {
                return this.orgCityField;
            }
            set {
                this.orgCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string routeType {
            get {
                return this.routeTypeField;
            }
            set {
                this.routeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string seatCode {
            get {
                return this.seatCodeField;
            }
            set {
                this.seatCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string jetquay {
            get {
                return this.jetquayField;
            }
            set {
                this.jetquayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gdsbook.gds.service.version1_0.webservice.model.ltips.com/")]
    public partial class wspnrssr {
        
        private string actionCodeField;
        
        private string airlineField;
        
        private string param1Field;
        
        private string param2Field;
        
        private string psgrIDField;
        
        private string sSRTypeField;
        
        private string serveInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string actionCode {
            get {
                return this.actionCodeField;
            }
            set {
                this.actionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string airline {
            get {
                return this.airlineField;
            }
            set {
                this.airlineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string psgrID {
            get {
                return this.psgrIDField;
            }
            set {
                this.psgrIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SSRType {
            get {
                return this.sSRTypeField;
            }
            set {
                this.sSRTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serveInfo {
            get {
                return this.serveInfoField;
            }
            set {
                this.serveInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gdsbook.gds.service.version1_0.webservice.model.ltips.com/")]
    public partial class wspnrrmk {
        
        private string param1Field;
        
        private string param2Field;
        
        private string psgrIDField;
        
        private string rmkInfoField;
        
        private int rmkTypeField;
        
        private bool rmkTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string psgrID {
            get {
                return this.psgrIDField;
            }
            set {
                this.psgrIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rmkInfo {
            get {
                return this.rmkInfoField;
            }
            set {
                this.rmkInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int rmkType {
            get {
                return this.rmkTypeField;
            }
            set {
                this.rmkTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rmkTypeSpecified {
            get {
                return this.rmkTypeFieldSpecified;
            }
            set {
                this.rmkTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gdsbook.gds.service.version1_0.webservice.model.ltips.com/")]
    public partial class wspnrPassenger {
        
        private int ageField;
        
        private bool ageFieldSpecified;
        
        private string idNumberField;
        
        private string idTypeField;
        
        private int lineIndexField;
        
        private bool lineIndexFieldSpecified;
        
        private string nameField;
        
        private string param1Field;
        
        private string param2Field;
        
        private string passengerTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ageSpecified {
            get {
                return this.ageFieldSpecified;
            }
            set {
                this.ageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idNumber {
            get {
                return this.idNumberField;
            }
            set {
                this.idNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idType {
            get {
                return this.idTypeField;
            }
            set {
                this.idTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int lineIndex {
            get {
                return this.lineIndexField;
            }
            set {
                this.lineIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lineIndexSpecified {
            get {
                return this.lineIndexFieldSpecified;
            }
            set {
                this.lineIndexFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passengerType {
            get {
                return this.passengerTypeField;
            }
            set {
                this.passengerTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gdsbook.gds.service.version1_0.webservice.model.ltips.com/")]
    public partial class wspnrosi {
        
        private string airlineField;
        
        private string osiField;
        
        private bool osi_tknoField;
        
        private string param1Field;
        
        private string param2Field;
        
        private string pNumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string airline {
            get {
                return this.airlineField;
            }
            set {
                this.airlineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string osi {
            get {
                return this.osiField;
            }
            set {
                this.osiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool osi_tkno {
            get {
                return this.osi_tknoField;
            }
            set {
                this.osi_tknoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pNum {
            get {
                return this.pNumField;
            }
            set {
                this.pNumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gdsbook.gds.service.version1_0.webservice.model.ltips.com/")]
    public partial class wspnrInfant {
        
        private System.DateTime brithField;
        
        private bool brithFieldSpecified;
        
        private string carrierField;
        
        private string nameField;
        
        private string nameInPnrField;
        
        private string param1Field;
        
        private string param2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime brith {
            get {
                return this.brithField;
            }
            set {
                this.brithField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool brithSpecified {
            get {
                return this.brithFieldSpecified;
            }
            set {
                this.brithFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string carrier {
            get {
                return this.carrierField;
            }
            set {
                this.carrierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nameInPnr {
            get {
                return this.nameInPnrField;
            }
            set {
                this.nameInPnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gdsbook.gds.service.version1_0.webservice.model.ltips.com/")]
    public partial class wspnrfn {
        
        private string airportTaxField;
        
        private string commisionField;
        
        private string fuelTaxField;
        
        private bool infantFlagField;
        
        private string param1Field;
        
        private string param2Field;
        
        private string salePriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string airportTax {
            get {
                return this.airportTaxField;
            }
            set {
                this.airportTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string commision {
            get {
                return this.commisionField;
            }
            set {
                this.commisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fuelTax {
            get {
                return this.fuelTaxField;
            }
            set {
                this.fuelTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool infantFlag {
            get {
                return this.infantFlagField;
            }
            set {
                this.infantFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string salePrice {
            get {
                return this.salePriceField;
            }
            set {
                this.salePriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gdsbook.gds.service.version1_0.webservice.model.ltips.com/")]
    public partial class wspnrOther {
        
        private string otherField;
        
        private string param1Field;
        
        private string param2Field;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string other {
            get {
                return this.otherField;
            }
            set {
                this.otherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gdsbook.gds.service.version1_0.webservice.model.ltips.com/")]
    public partial class wspnrContact {
        
        private string cityField;
        
        private string contactField;
        
        private int lineIndexField;
        
        private bool lineIndexFieldSpecified;
        
        private string param1Field;
        
        private string param2Field;
        
        private string psgrIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int lineIndex {
            get {
                return this.lineIndexField;
            }
            set {
                this.lineIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lineIndexSpecified {
            get {
                return this.lineIndexFieldSpecified;
            }
            set {
                this.lineIndexFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string psgrID {
            get {
                return this.psgrIDField;
            }
            set {
                this.psgrIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gdsbook.gds.service.version1_0.webservice.model.ltips.com/")]
    public partial class wspnrResult {
        
        private string contactInfoField;
        
        private wspnrContact[] contactsField;
        
        private wspnrOther[] eiField;
        
        private wspnrOther[] fcField;
        
        private wspnrfn[] fnField;
        
        private wspnrOther[] fpField;
        
        private string groupNameField;
        
        private int groupNumField;
        
        private bool groupNumFieldSpecified;
        
        private wspnrInfant[] infantsField;
        
        private bool isGroupField;
        
        private bool isGroupFieldSpecified;
        
        private wspnrosi[] oSIField;
        
        private string officeField;
        
        private string param1Field;
        
        private string param2Field;
        
        private wspnrPassenger[] passengersField;
        
        private string pnrField;
        
        private wspnrrmk[] rMKField;
        
        private string reservationField;
        
        private wspnrssr[] sSRField;
        
        private wspnrAirSegment[] segmentsField;
        
        private wspnrTktNo[] ticketNosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contactInfo {
            get {
                return this.contactInfoField;
            }
            set {
                this.contactInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contacts", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public wspnrContact[] contacts {
            get {
                return this.contactsField;
            }
            set {
                this.contactsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EI", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public wspnrOther[] EI {
            get {
                return this.eiField;
            }
            set {
                this.eiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FC", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public wspnrOther[] FC {
            get {
                return this.fcField;
            }
            set {
                this.fcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FN", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public wspnrfn[] FN {
            get {
                return this.fnField;
            }
            set {
                this.fnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FP", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public wspnrOther[] FP {
            get {
                return this.fpField;
            }
            set {
                this.fpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string groupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int groupNum {
            get {
                return this.groupNumField;
            }
            set {
                this.groupNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool groupNumSpecified {
            get {
                return this.groupNumFieldSpecified;
            }
            set {
                this.groupNumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("infants", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public wspnrInfant[] infants {
            get {
                return this.infantsField;
            }
            set {
                this.infantsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isGroup {
            get {
                return this.isGroupField;
            }
            set {
                this.isGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isGroupSpecified {
            get {
                return this.isGroupFieldSpecified;
            }
            set {
                this.isGroupFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OSI", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public wspnrosi[] OSI {
            get {
                return this.oSIField;
            }
            set {
                this.oSIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string office {
            get {
                return this.officeField;
            }
            set {
                this.officeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("passengers", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public wspnrPassenger[] passengers {
            get {
                return this.passengersField;
            }
            set {
                this.passengersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pnr {
            get {
                return this.pnrField;
            }
            set {
                this.pnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RMK", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public wspnrrmk[] RMK {
            get {
                return this.rMKField;
            }
            set {
                this.rMKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reservation {
            get {
                return this.reservationField;
            }
            set {
                this.reservationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SSR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public wspnrssr[] SSR {
            get {
                return this.sSRField;
            }
            set {
                this.sSRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("segments", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public wspnrAirSegment[] segments {
            get {
                return this.segmentsField;
            }
            set {
                this.segmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ticketNos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public wspnrTktNo[] ticketNos {
            get {
                return this.ticketNosField;
            }
            set {
                this.ticketNosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gdsbook.gds.service.version1_0.webservice.model.ltips.com/")]
    public partial class wspatItemt {
        
        private double airportTaxField;
        
        private double fuelTaxField;
        
        private int lineIndexField;
        
        private bool lineIndexFieldSpecified;
        
        private double parPriceField;
        
        private string param1Field;
        
        private string param2Field;
        
        private string seatClassField;
        
        private double totalPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double airportTax {
            get {
                return this.airportTaxField;
            }
            set {
                this.airportTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double fuelTax {
            get {
                return this.fuelTaxField;
            }
            set {
                this.fuelTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int lineIndex {
            get {
                return this.lineIndexField;
            }
            set {
                this.lineIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lineIndexSpecified {
            get {
                return this.lineIndexFieldSpecified;
            }
            set {
                this.lineIndexFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double parPrice {
            get {
                return this.parPriceField;
            }
            set {
                this.parPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string seatClass {
            get {
                return this.seatClassField;
            }
            set {
                this.seatClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double totalPrice {
            get {
                return this.totalPriceField;
            }
            set {
                this.totalPriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gdsbook.gds.service.version1_0.webservice.model.ltips.com/")]
    public partial class wspatResult {
        
        private string param1Field;
        
        private string param2Field;
        
        private string passengerTypeField;
        
        private wspatItemt[] patItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string passengerType {
            get {
                return this.passengerTypeField;
            }
            set {
                this.passengerTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("patItems", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public wspatItemt[] patItems {
            get {
                return this.patItemsField;
            }
            set {
                this.patItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(gdsBookingReply))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gdsbook.gds.service.version1_0.webservice.model.ltips.com/")]
    public abstract partial class abstractLiantuoReply {
        
        private string returnCodeField;
        
        private string returnMessageField;
        
        private string returnStackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string returnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string returnStackTrace {
            get {
                return this.returnStackTraceField;
            }
            set {
                this.returnStackTraceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gdsbook.gds.service.version1_0.webservice.model.ltips.com/")]
    public partial class gdsBookingReply : abstractLiantuoReply {
        
        private string param1Field;
        
        private string param2Field;
        
        private string param3Field;
        
        private wspatResult[] patResultField;
        
        private string patTxtField;
        
        private string pnrNoField;
        
        private wspnrResult pnrResultField;
        
        private string pnrTxtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param3 {
            get {
                return this.param3Field;
            }
            set {
                this.param3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("patResult", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public wspatResult[] patResult {
            get {
                return this.patResultField;
            }
            set {
                this.patResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string patTxt {
            get {
                return this.patTxtField;
            }
            set {
                this.patTxtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pnrNo {
            get {
                return this.pnrNoField;
            }
            set {
                this.pnrNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wspnrResult pnrResult {
            get {
                return this.pnrResultField;
            }
            set {
                this.pnrResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pnrTxt {
            get {
                return this.pnrTxtField;
            }
            set {
                this.pnrTxtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gdsbook.gds.service.version1_0.webservice.model.ltips.com/")]
    public partial class wsBookingSegment {
        
        private string arrTimeField;
        
        private string depDateField;
        
        private string depTimeField;
        
        private string dstCodeField;
        
        private string flightNoField;
        
        private string orgCodeField;
        
        private string param1Field;
        
        private string param2Field;
        
        private string param3Field;
        
        private string routeTypeField;
        
        private string seatClassField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arrTime {
            get {
                return this.arrTimeField;
            }
            set {
                this.arrTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string depDate {
            get {
                return this.depDateField;
            }
            set {
                this.depDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string depTime {
            get {
                return this.depTimeField;
            }
            set {
                this.depTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dstCode {
            get {
                return this.dstCodeField;
            }
            set {
                this.dstCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string flightNo {
            get {
                return this.flightNoField;
            }
            set {
                this.flightNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orgCode {
            get {
                return this.orgCodeField;
            }
            set {
                this.orgCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string param3 {
            get {
                return this.param3Field;
            }
            set {
                this.param3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string routeType {
            get {
                return this.routeTypeField;
            }
            set {
                this.routeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string seatClass {
            get {
                return this.seatClassField;
            }
            set {
                this.seatClassField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(gdsBookingRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gdsbook.gds.service.version1_0.webservice.model.ltips.com/")]
    public abstract partial class abstractLiantuoRequest {
        
        private string agencyCodeField;
        
        private string signField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string agencyCode {
            get {
                return this.agencyCodeField;
            }
            set {
                this.agencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sign {
            get {
                return this.signField;
            }
            set {
                this.signField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void gdsBookingCompletedEventHandler(object sender, gdsBookingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class gdsBookingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal gdsBookingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public gdsBookingReply Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((gdsBookingReply)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591